name: aiw3defi-test
description: AIW3 DeFi bank send transactions test
client_factory: aiw3defi-bank-send
connections: 5
duration: 1m0s
send_period: 1s
transactions_per_second: 500
transaction_size: 512
transaction_count: -1
broadcast_method: sync
endpoints:
    - ws://localhost:26657/websocket
endpoint_select_method: supplied
expect_peers: 0
max_endpoints: 0
min_connectivity: 0
peer_connect_timeout: 5s
tags:
    - aiw3
    - defi
    - bank-send
created_at: 2025-06-18T06:58:33.296973924Z
