name: aiw3-devnet
description: AIW3 Devnet load testing configuration with multi-endpoint support
client_factory: aiw3defi-bank-send
connections: 2
duration: 30s
send_period: 1s
transactions_per_second: 50
transaction_size: 512
transaction_count: -1
broadcast_method: sync
endpoints:
  - https://devnet-rpc.aiw3.io
  - https://devnet-api.aiw3.io
endpoint_select_method: supplied
expect_peers: 0
max_endpoints: 0
min_connectivity: 0
peer_connect_timeout: 5s
tags:
  - aiw3
  - devnet
  - bank-send
  - multi-endpoint
created_at: 2025-06-18T15:52:30Z
updated_at: 2025-06-18T15:52:30Z 